### PR TITLE
fix(core): new pathway to apply namespace targeted decorators

### LINKED ISSUE #874: DCS with namespace target, don't apply decorators on top of the namespace.
# Bug Report 🐛

The following model definition is valid...

```
@Term("My HR Model")
@Term_description("Reusable data definitions for the HR department.")
namespace acme.hr@1.0.0
```

## Current Behavior
When we apply decorator using dcs targeting the namespace,
```
{
        "$class": "org.accordproject.decoratorcommands@0.3.0.DecoratorCommandSet",
        "name": "web",
        "version": "1.0.0",
        "commands": [
            {
                "$class": "org.accordproject.decoratorcommands@0.3.0.Command",
                "type": "UPSERT",
                "target": {
                    "$class": "org.accordproject.decoratorcommands@0.3.0.CommandTarget",
                    "namespace": "test@1.0.0"
                },
                "decorator": {
                    "$class": "concerto.metamodel@1.0.0.Decorator",
                    "name": "Form",
                    "arguments": [
                        {
                            "$class": "concerto.metamodel@1.0.0.DecoratorString",
                            "value": "inputType"
                        },
                        {
                            "$class": "concerto.metamodel@1.0.0.DecoratorString",
                            "value": "text"
                        }
                    ]
                }
            }
        ]
    }
```
We get the following output
```
namespace test@1.0.0

@Form("inputType","text")
scalar SSN extends String

@Editable
@Form("inputType","text")
concept Person {
  @Custom
  o String firstName
  o String lastName
  o String bio
  o SSN ssn
  o String address1
  o String address2
  o String city
  o String country
  o Integer zip
  o Dictionary dictionary
}

@Form("inputType","text")
map Dictionary {
  o String
  o String
}

@Form("inputType","text")
map Rolodex {
  o String
  o String
}
```

## Expected Behavior

We should get the following output:
```
@Form("inputType","text")
namespace test@1.0.0

scalar SSN extends String

@Editable
concept Person {
  @Custom
  o String firstName
  o String lastName
  o String bio
  o SSN ssn
  o String address1
  o String address2
  o String city
  o String country
  o Integer zip
  o Dictionary dictionary
}

map Dictionary {
  o String
  o String
}

map Rolodex {
  o String
  o String
}
```

## Possible Solution

1. Breaking change - fix the logic which targets namespace. This would be a breaking change for the users who use namespace targeted dcs to apply decorators to all the decorators in that namespace.
2. Introduce a new property `applyToAllDeclarationsInNamespace` or something better, which defaults to true. Can be set to `false` if we don't want to apply to declaration and only at the top of the namespace. Validation could be tricky and would be confusing for users to pickup.
3. New target option `target: "something-new"`, which would target only the namespace, 

I'm more inclined towards the first options if we are able check if the impact is minimal or null. Or else the 3rd option, but I feel we will have to come up with some property value for the target that signal that this is for applying decorator at the top of a namespace, which I feel `namespace` itself conveys the best.

## Steps to Reproduce

https://replit.com/@sanketshevkar/AccordProjectConcerto-Decorator-Command-Set

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

### PR DESCRIPTION
**Pull request by sanketshevkar**
# Closes #874 

### Changes

- Introduce new feature flag accessed using optional parameters and as environment variable to enable new pathway
- When flags disabled, namespace targeted dcs would be get applied to all declarations within a namespace and if enabled just on top of the namespace.
- A new warning emitter pattern introduced to emit deprecation warning. 

### Flags

- <ONE>
- <TWO>

### Related Issues
- Issue #874 

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `main` from `fork:branchname`

### CODE REVIEW

File: packages/concerto-util/lib/warning.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+/**
+ * Emits DeprecationWaring to stderr only once and can be caught using an warning event listener as well, please define the code
+ * and document the deprecation code on https://concerto.accordproject.org/depreaction
+ * @param {string} message - message of the deprecation warning
+ * @param {string} type - type of the deprecation warning
+ * @param {string} code - code of the deprecation warning
+ * @param {string} detail - detail of the deprecation warning
+ */
+function printDeprecationWarning(message, type, code, detail) {
```
Comment (sanketshevkar) [inline packages/concerto-util/lib/warning.js:27]: I'll fix the coverage if we are happy with the warning emitter design.

File: packages/concerto-core/index.js [hunk 2]
```diff
@@ -102,6 +102,9 @@ const Concerto = require('./lib/concerto');
 // MetaModel
 const MetaModel = require('./lib/introspect/metamodel');
 
+// ConcertoCodes
+const ConcertoCodes = require('./lib/concertoCodes');
```
Comment (mttrbrts) [inline packages/concerto-core/index.js:106]: We already have error codes, I believe. Should we consolidate with this? Or rename this to be deprecation-specific?

File: packages/concerto-core/lib/decoratormanager.js [hunk 3]
```diff
@@ -440,15 +446,35 @@ class DecoratorManager {
...
     }
 
+    /**
+     * Executes a Command against a Model Namespace, adding
+     * decorators to the Namespace.
+     * @param {*} model the model
+     * @param {*} command the Command object from the dcs
+     * org.accordproject.decoratorcommands model
+     */
+    static executeNamespaceCommand(model, command) {
```
Comment (mttrbrts) [inline packages/concerto-core/lib/decoratormanager.js:456]: This should be a private function, I believe?

File: packages/concerto-core/lib/decoratormanager.js [hunk 4]
```diff
@@ -511,6 +537,46 @@ class DecoratorManager {
...
+     */
+    static checkForNamespaceTarget(enableDcsNamespaceTarget) {
+        if(enableDcsNamespaceTarget || process.env.ENABLE_DCS_NAMESPACE_TARGET === 'true') {
+            return true;
+        } else {
+            Warning.printDeprecationWarning(
+                'Functionality for namespace targeted Decorator Command Sets has beed changed. Using namespace targets to apply decorators on all declarations in a namespace will be deprecated soon.',
+                ErrorCodes.DEPRECATION_WARNING,
+                ConcertoCodes.CONCERTO_DEPRECATION_001,
+                'Please refer See https://concerto.accordproject.org/depreaction#001'
```
Comment (mttrbrts) [inline packages/concerto-core/lib/decoratormanager.js:575]:
```suggestion
                'Please refer See https://concerto.accordproject.org/docs/reference/deprecation/001'
```

File: packages/concerto-core/lib/decoratormanager.js [hunk 5]
```diff
@@ -511,6 +537,46 @@ class DecoratorManager {
...
+        }
+    }
+
+    /**
+     * Checks if enableDcsNamespaceTarget or ENABLE_DCS_TARGET_NAMESPACE is enabled or not
+     * and print depreaction warning if not enabled and return boolean value as well
+     *  @param {boolean} [enableDcsNamespaceTarget] - flag to control applying namespace targeted decorators on top of the namespace instead of all declarations in that namespace
+     *  @returns {Boolean} true if either of the flags is enabled
+     */
+    static checkForNamespaceTarget(enableDcsNamespaceTarget) {
```
Comment (mttrbrts) [inline packages/concerto-core/lib/decoratormanager.js:567]:
```suggestion
    static isNamespaceTargetEnabled(enableDcsNamespaceTarget) {
```

File: packages/concerto-core/index.js (hunk 2 above)
Comment (mttrbrts) [reply packages/concerto-core/index.js:106]: Let's consolidate. I see that you're modifying Error Code already in this PR.

The Warning Codes should be part of concerto-util

File: packages/concerto-util/lib/warning.js [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+ * limitations under the License.
+ */
+
+'use strict';
+
+let isWarningEmitted = false;
+
+/**
+ * Emits DeprecationWaring to stderr only once and can be caught using an warning event listener as well, please define the code
+ * and document the deprecation code on https://concerto.accordproject.org/depreaction
```
Comment (mttrbrts) [inline packages/concerto-util/lib/warning.js:21]:
```suggestion
 * and document the deprecation code on https://concerto.accordproject.org/reference/deprecation
```

File: packages/concerto-util/lib/warning.js [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+ * @param {string} message - message of the deprecation warning
+ * @param {string} type - type of the deprecation warning
+ * @param {string} code - code of the deprecation warning
+ * @param {string} detail - detail of the deprecation warning
+ */
+function printDeprecationWarning(message, type, code, detail) {
+    if (!isWarningEmitted) {
+        isWarningEmitted = true;
```
Comment (mttrbrts) [inline packages/concerto-util/lib/warning.js:29]: I assume that in future, we'll want a flag per warning?

File: packages/concerto-core/api.txt [hunk 8]
```diff
@@ -59,13 +59,16 @@ class DecoratorExtractor {
...
 class DecoratorManager {
    + ModelManager validate(decoratorCommandSet,ModelFile[]) throws Error
-   + ModelManager decorateModels(ModelManager,decoratorCommandSet,object?,boolean?,boolean?,boolean?) 
+   + ModelManager decorateModels(ModelManager,decoratorCommandSet,object?,boolean?,boolean?,boolean?,boolean?) 
    + ExtractDecoratorsResult extractDecorators(ModelManager,object,boolean,string) 
    + void validateCommand(ModelManager,command) 
    + Boolean falsyOrEqual(string||,string[]) 
    + void applyDecorator(decorated,string,newDecorator) 
-   + void executeCommand(string,declaration,command) 
+   + void executeNamespaceCommand(model,command)
```
Comment (mttrbrts) [inline packages/concerto-core/api.txt:67]: This shouldn't be public

File: packages/concerto-core/api.txt [hunk 9]
```diff
@@ -59,13 +59,16 @@ class DecoratorExtractor {
...
+   + ModelManager decorateModels(ModelManager,decoratorCommandSet,object?,boolean?,boolean?,boolean?,boolean?) 
    + ExtractDecoratorsResult extractDecorators(ModelManager,object,boolean,string) 
    + void validateCommand(ModelManager,command) 
    + Boolean falsyOrEqual(string||,string[]) 
    + void applyDecorator(decorated,string,newDecorator) 
-   + void executeCommand(string,declaration,command) 
+   + void executeNamespaceCommand(model,command) 
+   + void executeCommand(string,declaration,command,boolean?) 
    + void executePropertyCommand(property,command) 
+   + void checkForNamespaceTargetAndApplyDecorator(declaration,string,decorator,target,boolean?)
```
Comment (mttrbrts) [inline packages/concerto-core/api.txt:70]: This shouldn't be public

File: packages/concerto-core/api.txt [hunk 10]
```diff
@@ -59,13 +59,16 @@ class DecoratorExtractor {
...
    + ExtractDecoratorsResult extractDecorators(ModelManager,object,boolean,string) 
    + void validateCommand(ModelManager,command) 
    + Boolean falsyOrEqual(string||,string[]) 
    + void applyDecorator(decorated,string,newDecorator) 
-   + void executeCommand(string,declaration,command) 
+   + void executeNamespaceCommand(model,command) 
+   + void executeCommand(string,declaration,command,boolean?) 
    + void executePropertyCommand(property,command) 
+   + void checkForNamespaceTargetAndApplyDecorator(declaration,string,decorator,target,boolean?) 
+   + Boolean checkForNamespaceTarget(boolean?)
```
Comment (mttrbrts) [inline packages/concerto-core/api.txt:71]: This shouldn't be public

File: packages/concerto-core/lib/introspect/modelfile.js [hunk 11]
```diff
@@ -746,6 +746,7 @@ class ModelFile extends Decorated {
                 if (this.getModelManager().isStrict()){
                     throw new Error('Wilcard Imports are not permitted in strict mode.');
                 }
+                // Should we change this as well?
```
Comment (mttrbrts) [inline packages/concerto-core/lib/introspect/modelfile.js:749]: Yes, let's move this to a proper deprecation too.

**Review by mttrbrts — CHANGES_REQUESTED** [review]

File: packages/concerto-util/lib/warning.js (hunk 7 above)
Comment (sanketshevkar) [reply packages/concerto-util/lib/warning.js:29]: Yes

File: packages/concerto-core/lib/introspect/modelfile.js (hunk 11 above)
Comment (sanketshevkar) [reply packages/concerto-core/lib/introspect/modelfile.js]: Done

File: packages/concerto-core/api.txt (hunk 9 above)
Comment (sanketshevkar) [reply packages/concerto-core/api.txt]: Corrected

File: packages/concerto-core/api.txt (hunk 8 above)
Comment (sanketshevkar) [reply packages/concerto-core/api.txt]: Corrected

File: packages/concerto-util/lib/warning.js (hunk 6 above)
Comment (sanketshevkar) [reply packages/concerto-util/lib/warning.js]: Corrected

File: packages/concerto-core/lib/decoratormanager.js (hunk 5 above)
Comment (sanketshevkar) [reply packages/concerto-core/lib/decoratormanager.js]: Corrected

File: packages/concerto-core/lib/decoratormanager.js (hunk 4 above)
Comment (sanketshevkar) [reply packages/concerto-core/lib/decoratormanager.js]: Done

File: packages/concerto-core/lib/decoratormanager.js (hunk 3 above)
Comment (sanketshevkar) [reply packages/concerto-core/lib/decoratormanager.js:455]: Corrected

File: packages/concerto-core/index.js (hunk 2 above)
Comment (sanketshevkar) [reply packages/concerto-core/index.js]: Yes moved them there

File: packages/concerto-util/lib/warning.js [hunk 12]
```diff
@@ -0,0 +1,40 @@
...
+ * and document the deprecation code on https://concerto.accordproject.org/deprecation
+ * @param {string} message - message of the deprecation warning
+ * @param {string} type - type of the deprecation warning
+ * @param {string} code - code of the deprecation warning
+ * @param {string} detail - detail of the deprecation warning
+ */
+function printDeprecationWarning(message, type, code, detail) {
+    if (!isWarningEmitted) {
+        isWarningEmitted = true;
+        process.emitWarning(`DEPRECATED: ${message}`, {
```
Comment (dselman) [inline packages/concerto-util/lib/warning.js:30]: `process.emitWarning` won't work in the browser without polyfill. We will need some way to control this, or this will break upstream usage of ModelManager, e.g. in the playground, VSCode etc.

**Review by dselman — CHANGES_REQUESTED** [review]
Concerto-Core needs to be usable within the web browser.

File: packages/concerto-util/lib/warning.js (hunk 12 above)
Comment (sanketshevkar) [reply packages/concerto-util/lib/warning.js]: Thanks for catching this. I've added a polyfill for this in the latest commit.

Comment (sanketshevkar) [reply packages/concerto-util/lib/warning.js]: I tested the build locally on my browser it seems to working

**Review by dselman — APPROVED** [review]

**Review by mttrbrts — APPROVED** [review]
