### PR TITLE
fix(core) Properly handles flags in string regex validators

### LINKED ISSUE #302: Regular expressions do not work with flags
# Bug Report 🐛

Regular expressions with flags e.g., `/^[a-zA-Z0-1]*^/u` do not work.

## Expected Behavior

Regular expressions should work with flags.

## Current Behavior

With the given CTO:

```
namespace org.test

concept Person {
	o String name regex=/^[a-zA-Z][a-zA-Z0-9]*$/u
	o Double age
}
```

And input data:
```
{
    "$class": "org.test.Person",
    "name": "John",
    "age": 33
}
```

The validation fails:

```
zsh-5.8$ concerto validate --model test.cto --input person.json
7:56:56 AM - INFO: Input is invalid
7:56:56 AM - ERROR: Validator error for field undefined org.test.Person.name: Value + 'John' failed to match validation regex: /^[a-zA-Z][a-zA-Z0-9]*$\//
Error: Validator error for field undefined org.test.Person.name: Value + 'John' failed to match validation regex: /^[a-zA-Z][a-zA-Z0-9]*$\//
    at StringValidator.reportError (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/introspect/validator.js:44:15)
    at StringValidator.validate (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/introspect/stringvalidator.js:56:22)
    at ResourceValidator.checkItem (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/serializer/resourcevalidator.js:327:42)
    at ResourceValidator.visitField (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/serializer/resourcevalidator.js:221:22)
    at ResourceValidator.visit (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/serializer/resourcevalidator.js:77:25)
    at Field.accept (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/introspect/decorated.js:65:24)
    at ResourceValidator.visitClassDeclaration (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/serializer/resourcevalidator.js:174:26)
    at ResourceValidator.visit (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/serializer/resourcevalidator.js:73:25)
    at ConceptDeclaration.accept (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/introspect/decorated.js:65:24)
    at ValidatedResource.validate (/usr/local/lib/node_modules/@accordproject/concerto-cli/node_modules/@accordproject/concerto-core/lib/model/validatedresource.js:125:26)

```

### PR DESCRIPTION
**Pull request by jeromesimeon**
Signed-off-by: jeromesimeon <jeromesimeon@me.com>

# Closes #302

### Changes

- Handles regular expressions with flags

### Flags

- Parser already supported them, but now string validation
- With this fix, we can properly handle complex regular expressions with unicode as needed to validate names in the metamodel (#298)

### CODE REVIEW

File: packages/concerto-core/lib/introspect/stringvalidator.js [hunk 1]
```diff
@@ -33,10 +33,18 @@ class StringValidator extends Validator{
      * @throws {IllegalModelException}
      */
     constructor(field, validator) {
-        super(field,validator);
+        super(field, validator);
         try {
-            // discard the leading / and closing /
-            this.regex = new RegExp(validator.substring(1,validator.length-1));
+            // Extract the RegExp components (pattern and flag)
+            const match = validator.match(/^\/([^/]*)\/(.*)$/);
```
Comment (mttrbrts) [inline packages/concerto-core/lib/introspect/stringvalidator.js:39]: I think that this will fail for regexes that include escaped slashed in the pattern, e.g. `/foo\/bar/u`
image

**Review by mttrbrts — CHANGES_REQUESTED** [review]

File: packages/concerto-core/lib/introspect/stringvalidator.js (hunk 1 above)
Comment (jeromesimeon) [reply packages/concerto-core/lib/introspect/stringvalidator.js:39]: yep! good catch.

**Review by mttrbrts — APPROVED** [review]
