### PR TITLE
Remove instanceof symbol

### LINKED ISSUE #47: Avoid `instanceof` which leads to runtime errors with deep npm dependencies
The use of `instanceof` to check whether an object is of a class leads to unreliable check when importing Composer Concerto in projects with deep npm dependencies.

## Context

Composer Concerto uses `instanceof` checks e.g., here https://github.com/hyperledger/composer-concerto/blob/37189e52c4f52d13cbd862b38d36a64022976398/lib/serializer/resourcevalidator.js#L72 or here https://github.com/hyperledger/composer-concerto/blob/37189e52c4f52d13cbd862b38d36a64022976398/lib/serializer/jsonpopulator.js#L96

Those can be unreliable since it checks whether this is the same object from the exact same package installed in a node.js project.

The reason it is unreliable is that it is difficult to enforce that the corresponding version of `composer-concerto` is installed exactly once in the `./node_modules` directory through `npm install`.

This can lead to runtime errors when doing validation/serialization in some projects with deep npm dependencies.

## Expected Behavior

A project should be able to import Composer Concerto 0.7.1 and PROJECT 0.X.X depending on e.g., Composer Concerto 0.7.0 without leading to runtime errors.

## Actual Behavior

Currently a project has to ensure _every_ dependency which import Composer Concerto have the exact same version, and that `npm install` leads to only one copy of that same version, which is difficult to guarantee (due to the way `npm install` works).

## Possible Fix

Several fixes are suggested in: https://stackoverflow.com/questions/41587865/using-instanceof-on-objects-created-with-constructors-from-deep-npm-dependenci

The recommended fix is to use an explicit method to check whether an object has the expected class. So instead of writing `thing instanceof RelationshipDeclaration` one would write `isRelationshipDeclaration(thing)` where:

```js
RelationshipDeclaration.prototype._isRelationshipDeclaration = true;
var isRelationshipDeclaration = function isRelationshipDeclaration(obj) {
  return obj instanceof RelationshipDeclaration || Boolean(obj._isRelationshipDeclaration);
};

module.exports = {
  RelationshipDeclaration,
  isRelationshipDeclaration
};
```

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [x] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [x] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Context

Importing Composer Concerto in various parts of the Accord Project (Ergo, Cicero, Cicero template library, template studio, etc.).

## Your Environment

* Version used: 0.70.*
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 8
* Operating System and version (desktop or mobile): MacOS
* Link to your project:

### PR DESCRIPTION
**Pull request by dselman**
# Closes #47
- Removes custom `hasInstance` code, which is incompatible with Babel
- Refactor code and tests to use new methods to determine the runtime types
- Removes support for Node 12, adds support for Node 16

### Flags
- API breaking change

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`

### CODE REVIEW

File: packages/concerto-core/lib/introspect/classdeclaration.js [hunk 1]
```diff
@@ -65,6 +65,7 @@ class ClassDeclaration extends Decorated {
         this.idField = null;
         this.timestamped = false;
         this.abstract = false;
+        this.type = this.ast.type;
```
Comment (jeromesimeon) [inline packages/concerto-core/lib/introspect/classdeclaration.js:68]: oh no! that one's going to be  😭

File: packages/concerto-core/lib/introspect/metamodel.js [hunk 2]
```diff
@@ -19,1069 +19,1069 @@ const ModelManager = require('../modelmanager');
 const Factory = require('../factory');
 const Serializer = require('../serializer');
 
+const metaModelCto = `/*
```
Comment (jeromesimeon) [inline packages/concerto-core/lib/introspect/metamodel.js:22]: Why changes to this file? That seems unrelated to `instanceof` ? I would remove those changes to avoid conflicts with the other PRs on the new parser.

**Review by jeromesimeon — CHANGES_REQUESTED** [review]
Looks great! Just one change request on the `metamodel.js` file.

File: packages/concerto-core/lib/introspect/metamodel.js (hunk 2 above)
Comment (dselman) [reply packages/concerto-core/lib/introspect/metamodel.js:22]: Ok, I will remove

**Review by jeromesimeon — APPROVED** [review]
LGTM!
